#!/usr/bin/env python

import sys
import numpy as np
from optparse import OptionParser
from oppvasp.vasp.parsers import PoscarParser

parser = OptionParser( usage = "usage: %prog [options] OLDFILE NEWFILE" )
parser.add_option('-a', '--abs_all', action='store_true', dest = 'abs', default = False)
parser.add_option('-n', '--norm_all', action='store_true', dest = 'norm', default = False)
parser.add_option('-d', '--diff_all', action='store_true', dest = 'diff', default = False)
(options, args) = parser.parse_args()
if len(args) != 2:
    print "Please provide the filename of two POSCAR-type files to compare"
    parser.print_usage()
    sys.exit(1)

poscar1 = PoscarParser(args[0]).get_structure()
poscar2 = PoscarParser(args[1]).get_structure()

cell1 = poscar1.get_cell()
cell2 = poscar2.get_cell()

pos1 = poscar1.get_positions('cart') 
pos2 = poscar2.get_positions('cart')

if np.allclose(cell1, cell2, rtol = 1.e-5, atol = 1.e-8):
    print "The unit cell did not change"
else:
    print "Unit cell change:"
    print cell2-cell1


if np.allclose(pos1, pos2, rtol = 1.e-5, atol = 1.e-8):
    print "The two files are practically the same. \n" \
        + "For all coordinates, \n" \
        + "   absolute(a - b) <= (atol + rtol * absolute(b)), \n" \
        + "where rtol = 1.e-5 and atol = 1.e-8"
else:
    diff = pos2 - pos1
    norms = np.sqrt(np.sum((pos2-pos1)**2,axis=1))
    
    if options.norm:
        print "Displacements in Angstrom:"
        for i,n in enumerate(norms):
            print "%5d : %.5f" % ((i+1),n)

    if options.abs:
        print "Absolute diff:"
        print np.abs(diff)

    if options.diff:
        print "Diff:"
        print diff

    max_idx = np.argmax(norms)
    min_idx = np.argmin(norms)
    mean_disp = np.mean(norms)
    print "Mean displacement: %.3f Angstrom" % (mean_disp)
    print "  in x direction: %.3f, y direction: %.3f, z-direction: %.3f " % (np.mean(diff[:,0]), np.mean(diff[:,1]), np.mean(diff[:,2]))
    print "Min displacement: %.3f Angstrom (atom no. %d)" % (norms[min_idx], min_idx)
    print "Max displacement: %.3f Angstrom (atom no. %d)" % (norms[max_idx], max_idx)

