#!/usr/bin/env python

import sys
import numpy as np
from optparse import OptionParser
from oppvasp.vasp.parsers import PoscarParser

inputfile = 'POSCAR'
parser = OptionParser( usage = "usage: %prog [options] POSCAR" )
(options, args) = parser.parse_args()
if len(args) > 0:
    inputfile = args[0]

struct = PoscarParser(inputfile).get_structure()
struct.save('POSCAR.2', direct_coords = True)
