#!/usr/bin/env python

from oppvasp.vasp.parsers import PoscarParser
import numpy as np
from optparse import OptionParser

parser = OptionParser()
(options, args) = parser.parse_args()
if len(args) != 2:
    print "Please provide the filename of two POSCAR-type files to compare"
    sys.exit(1)

poscar1 = PoscarParser(args[0]).get_structure()
poscar2 = PoscarParser(args[1]).get_structure()

pos1 = poscar1.get_positions('cart') 
pos2 = poscar2.get_positions('cart')

if np.allclose(pos1, pos2, rtol = 1.e-5, atol = 1.e-8):
    print "The two files are practically the same. \n" \
        + "For all coordinates, \n" \
        + "   absolute(a - b) <= (atol + rtol * absolute(b)), \n" \
        + "where rtol = 1.e-5 and atol = 1.e-8"
else:
    print "Diff:"
    print pos2 - pos1
    #print np.abs(pos2 - pos1)

