#!/usr/bin/env python

"""
Read out the final structure from a vasprun.xml file,
create an ASE Atoms object and use ASE to write a POSCAR file.
"""

import sys
from oppvasp.vasp.parsers import VasprunParser

from optparse import OptionParser
parser = OptionParser( usage = "usage: %prog [vasprun.xml] [POSCAR]" ) 
(options, args) = parser.parse_args()

in_file = 'vasprun.xml'
out_file = 'POSCAR'
if len(args) > 0:
    in_file = args[0]
if len(args) > 1:
    out_file = args[1]
if len(args) > 2:
    print "Error: Too many arguments"
    parser.print_usage()
    sys.exit(1)

parser = VasprunParser(in_file)
print "Read %s" % (in_file)
mol = parser.get_final_structure()
mol.save(out_file)
print "Wrote %s" % (out_file)

#mol = parser.get_final_structure().get_ase_atoms_object()
#mol.write(out_file, format = 'vasp') # does not include atom types (labels)
#print "Wrote %s" % (out_file)

